name: Build Debian Package

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'  # 每天UTC时间20:00运行 (对应北京时间次日凌晨4:00)

jobs:
  build-debian-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone smartdns repository
        run: |
          git clone https://github.com/pymumu/smartdns.git

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config

      - name: Build SmartDNS Debian package
        run: |
          cd smartdns
          chmod +x package/build-pkg.sh
          ./package/build-pkg.sh --platform debian --arch amd64 --with-ui --static

      - name: Push to Releases branch
        run: |
          # 配置git用户
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # 切换到Releases分支或创建它
          git checkout Releases 2>/dev/null || git checkout -b Releases
          
          # 如果分支已存在，先拉取远程更改
          if git branch -r | grep -q "origin/Releases"; then
            git pull origin Releases --rebase || echo "Pull failed, continuing with local changes"
          fi
          
          # 删除Releases分支上原来的deb包
          git rm --ignore-unmatch *.deb 2>/dev/null || true
          
          # 仅上传新生成的deb包
          cd smartdns
          DEB_FILE=$(find . -name "*.deb" | head -n 1)
          if [ -n "$DEB_FILE" ]; then
            cp "$DEB_FILE" ..
            cd ..
            git add *.deb
          else
            echo "No deb package found to upload!"
            exit 1
          fi
          
          # 检查是否有更改需要提交
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update SmartDNS Debian package $(date '+%Y-%m-%d %H:%M:%S')"
            # 使用强制推送以确保成功
            git push origin Releases --force
          fi

      - name: Clean up
        run: |
          rm -rf smartdns
